import * as THREE from 'three';
import { OrbitControls } from 'three/addons/controls/OrbitControls.js';
import { GLTFExporter } from 'three/addons/exporters/GLTFExporter.js';
import './style.css';

const $ = id => document.getElementById(id);
const viewport = $('viewport');
const scene = new THREE.Scene(); scene.background = new THREE.Color('#10283c'); scene.fog = new THREE.FogExp2('#10283c',.018);
const camera = new THREE.PerspectiveCamera(43,1,.1,100); camera.position.set(12,11,17);
const renderer = new THREE.WebGLRenderer({antialias:true,preserveDrawingBuffer:true}); renderer.setPixelRatio(Math.min(devicePixelRatio||1,2)); renderer.outputColorSpace=THREE.SRGBColorSpace; renderer.toneMapping=THREE.ACESFilmicToneMapping; renderer.toneMappingExposure=1.7; viewport.appendChild(renderer.domElement);
const controls=new OrbitControls(camera,renderer.domElement); controls.enableDamping=true; controls.minDistance=8;controls.maxDistance=30;controls.maxPolarAngle=Math.PI*.48;controls.target.set(0,.7,0);
const hemi=new THREE.HemisphereLight('#e1f5f0','#10283c',2.1);scene.add(hemi); const sun=new THREE.DirectionalLight('#ffdbbf',3.5);sun.position.set(-6,11,8);scene.add(sun);const glow=new THREE.PointLight('#7bded4',42,17);glow.position.set(2,5,-1);scene.add(glow);
const world=new THREE.Group();scene.add(world);const stars=new THREE.Group();scene.add(stars);const ray=new THREE.Raycaster();const pointer=new THREE.Vector2();let current=null,night=false,groups=[],awakened=new Set();
function resize(){let w=viewport.clientWidth,h=viewport.clientHeight;if(!w||!h)return;camera.aspect=w/h;camera.updateProjectionMatrix();renderer.setSize(w,h,false)}new ResizeObserver(resize).observe(viewport);
const mat=(c,opt={})=>new THREE.MeshStandardMaterial({color:c,roughness:.5,metalness:.15,...opt});
function put(g,m,p,x=0,y=0,z=0){let n=new THREE.Mesh(g,m);n.position.set(x,y,z);p.add(n);return n}
function label(text,p){let c=document.createElement('canvas');c.width=512;c.height=128;let x=c.getContext('2d');x.fillStyle='rgba(15,37,53,.88)';x.beginPath();x.roundRect(10,15,492,96,28);x.fill();x.strokeStyle='rgba(231,241,229,.35)';x.lineWidth=2;x.stroke();x.fillStyle='#edf2e8';x.font='600 42px sans-serif';x.textAlign='center';x.textBaseline='middle';x.fillText(text,256,64,452);let s=new THREE.Sprite(new THREE.SpriteMaterial({map:new THREE.CanvasTexture(c),transparent:true,depthWrite:false}));s.scale.set(2.4,.6,1);s.position.y=3.6;p.add(s)}
function artifact(o,colors){let p=new THREE.Group();p.position.set(...o.position);p.userData.id=o.id;world.add(p);let ivory=mat('#e6eee9'),aqua=mat(colors[1],{emissive:colors[1],emissiveIntensity:.18}),amber=mat(colors[2],{emissive:colors[2],emissiveIntensity:.12}),dark=mat('#33596b',{metalness:.45});put(new THREE.CylinderGeometry(1.15,1.35,.28,32),dark,p,0,.04);put(new THREE.TorusGeometry(1.18,.025,8,64),amber,p,0,.2).rotation.x=Math.PI/2;
if(o.type==='tree'){put(new THREE.CylinderGeometry(.18,.3,1.45,9),amber,p,0,1);put(new THREE.ConeGeometry(.88,1.35,8),aqua,p,0,2.13);put(new THREE.ConeGeometry(.62,1.12,8),aqua,p,0,2.78)}
else if(o.type==='crystal'){put(new THREE.OctahedronGeometry(.93),aqua,p,0,1.63).scale.y=1.55;put(new THREE.OctahedronGeometry(.45),ivory,p,-.68,.76,.4)}
else if(o.type==='tower'){put(new THREE.CylinderGeometry(.53,.68,2.25,10),ivory,p,0,1.32);put(new THREE.ConeGeometry(.75,.77,10),amber,p,0,2.84);[.8,1.35,1.9].forEach(y=>put(new THREE.BoxGeometry(.27,.25,.045),aqua,p,0,y,.65))}
else if(o.type==='orb'){put(new THREE.SphereGeometry(.85,32,18),aqua,p,0,1.64);put(new THREE.TorusGeometry(1.04,.045,8,64),amber,p,0,1.64).rotation.x=1.05;put(new THREE.TorusGeometry(1.08,.027,8,64),ivory,p,0,1.64).rotation.y=1.1}
else if(o.type==='arch'||o.type==='portal'){put(new THREE.TorusGeometry(1.1,.18,14,64,Math.PI),o.type==='portal'?aqua:ivory,p,0,1.42);put(new THREE.CylinderGeometry(.22,.28,1.4,12),amber,p,-1.11,.85);put(new THREE.CylinderGeometry(.22,.28,1.4,12),amber,p,1.11,.85);if(o.type==='portal')put(new THREE.CircleGeometry(.9,48),new THREE.MeshBasicMaterial({color:colors[1],transparent:true,opacity:.2,side:THREE.DoubleSide}),p,0,1.3)}
else{put(new THREE.BoxGeometry(1.2,1.45,.23),aqua,p,0,1.31).rotation.z=-.18;put(new THREE.BoxGeometry(.97,1.21,.26),ivory,p,.1,1.32,-.07).rotation.z=-.18}
label(o.name,p);p.scale.setScalar(o.scale);groups.push(p)}
function starfield(){let points=[];for(let i=0;i<170;i++){let r=8+Math.random()*12,a=Math.random()*Math.PI*2;points.push(Math.cos(a)*r,2+Math.random()*10,Math.sin(a)*r)}let g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(points,3));stars.add(new THREE.Points(g,new THREE.PointsMaterial({color:'#d5edf0',size:.065,transparent:true,opacity:.65})))}starfield();
function show(data){while(world.children.length)world.remove(world.children[0]);groups=[];awakened=new Set();current=data;let c=data.plan.colors;scene.background=new THREE.Color(c[0]);scene.fog.color=new THREE.Color(c[0]);glow.color=new THREE.Color(c[1]);put(new THREE.CylinderGeometry(6.2,5.6,.7,80),mat('#244c60',{metalness:.23,roughness:.85}),world,0,-.55);put(new THREE.TorusGeometry(6.17,.035,10,100),mat(c[1],{emissive:c[1],emissiveIntensity:.5}),world,0,-.19).rotation.x=Math.PI/2;[2,4.3].forEach(r=>put(new THREE.RingGeometry(r,r+.012,100),new THREE.MeshBasicMaterial({color:'#b3d5df',transparent:true,opacity:.17,side:THREE.DoubleSide}),world,0,-.19).rotation.x=-Math.PI/2);data.scene.objects.forEach(o=>artifact(o,c));$('title').textContent=data.plan.title;$('subtitle').textContent=data.plan.subtitle;$('opening').textContent=data.story.opening;$('run-id').textContent=data.run_id.split('-').at(-1).toUpperCase();$('theme').textContent=data.plan.theme.toUpperCase();$('badge').textContent=data.manifest.mode==='nvidia_nemotron'?'● NVIDIA NEMOTRON':'◇ TEMPLATE MODE';$('provenance').textContent=data.manifest.mode==='nvidia_nemotron'?`NVIDIA 模型：${data.plan.provenance.model} · 契约 ${data.evaluation.status}`:`模板回退：${data.plan.provenance.fallback_reason} · 契约 ${data.evaluation.status}`;$('trace-status').textContent=data.evaluation.status;[...$('trace').children].forEach(e=>e.classList.add('done'));$('export').disabled=false;$('export-glb').disabled=false;$('export-status').textContent='';$('counter').textContent='0 / 6 节点已唤醒';$('icon').textContent='✧';$('caption').textContent='SELECT AN OBJECT';$('object-title').textContent='点击场景中的物件';$('object-story').textContent='每个物件都会响应你，并展开一个故事节点。'}
renderer.domElement.addEventListener('click',e=>{if(!current)return;let b=renderer.domElement.getBoundingClientRect();pointer.set((e.clientX-b.left)/b.width*2-1,-(e.clientY-b.top)/b.height*2+1);ray.setFromCamera(pointer,camera);for(let hit of ray.intersectObjects(groups,true)){let n=hit.object;while(n&&!n.userData.id)n=n.parent;if(!n?.userData.id)continue;let id=n.userData.id,o=current.scene.objects.find(x=>x.id===id);if(awakened.has(id))awakened.delete(id);else awakened.add(id);$('icon').textContent=awakened.has(id)?'✹':'✧';$('caption').textContent=awakened.has(id)?'NODE AWAKENED':'NODE AT REST';$('object-title').textContent=o.name;$('object-story').textContent=o.story;$('counter').textContent=`${awakened.size} / 6 节点已唤醒`;if(awakened.size===6)$('opening').textContent=current.story.ending;break}});
async function build(prompt,mode){let b=document.querySelector('.build');b.disabled=true;$('build-label').textContent='正在构建世界…';$('trace-status').textContent='运行中';[...$('trace').children].forEach(e=>e.classList.remove('done'));try{let r=await fetch('/api/build',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({prompt,mode})});let d=await r.json();if(!r.ok)throw new Error(d.detail||d.error);show(d)}catch(e){$('trace-status').textContent='失败';$('provenance').textContent=`构建失败：${e.message}。请检查服务并重试。`}finally{b.disabled=false;$('build-label').textContent='重新生成场景'}}
$('form').addEventListener('submit',e=>{e.preventDefault();build($('prompt').value,$('mode').value)});document.querySelectorAll('[data-example]').forEach(b=>b.addEventListener('click',()=>{$('prompt').value=b.dataset.example;build($('prompt').value,$('mode').value)}));$('reset').addEventListener('click',()=>{camera.position.set(12,11,17);controls.target.set(0,.7,0);controls.update()});$('daynight').addEventListener('click',()=>{night=!night;sun.intensity=night?.6:3.5;hemi.intensity=night?1.05:2.1;glow.intensity=night?65:42;$('daynight').textContent=night?'☀':'☾'});$('screenshot').addEventListener('click',()=>{let a=document.createElement('a');a.download=`worldstage-${current?.run_id||'scene'}.png`;a.href=renderer.domElement.toDataURL('image/png');a.click()});$('export').addEventListener('click',()=>{if(!current)return;let u=URL.createObjectURL(new Blob([JSON.stringify(current,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=u;a.download=`worldstage-${current.run_id}.json`;a.click();URL.revokeObjectURL(u)});$('export-glb').addEventListener('click',async()=>{if(!current)return;const button=$('export-glb');button.disabled=true;try{const exporter=new GLTFExporter();const data=await exporter.parseAsync(world,{binary:true,onlyVisible:true});$('export-status').textContent=`GLB 已生成 · ${(data.byteLength/1024).toFixed(0)} KB`;const url=URL.createObjectURL(new Blob([data],{type:'model/gltf-binary'}));const a=document.createElement('a');a.href=url;a.download=`worldstage-${current.run_id}.glb`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}catch(error){$('export-status').textContent=`3D 导出失败：${error.message}`}finally{button.disabled=false}});fetch('/api/health').then(r=>r.json()).then(d=>$('runtime').textContent=d.model_configured?'Nemotron 已配置':'模板模式可用').catch(()=>$('runtime').textContent='服务未连接');
let t=0;function animate(){requestAnimationFrame(animate);t+=.01;controls.update();stars.rotation.y+=.00016;groups.forEach((g,i)=>{let on=awakened.has(g.userData.id);g.position.y=Math.sin(t*(on?1.6:.75)+i)*(on?.14:.055);let s=(current?.scene.objects[i]?.scale||1)*(on?1.09:1);g.scale.lerp(new THREE.Vector3(s,s,s),.06);g.rotation.y+=on?.002:.00045});renderer.render(scene,camera)}resize();animate();build($('prompt').value,'template');
